name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  clang_format_check:
    name: Clang Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add LLVM repository
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
          sudo apt-get update
      - name: Install clang-format
        run: sudo apt-get install -y clang-format-10
      - name: Check code formatting
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)' -exec clang-format-10 -style=file -i {} \;
          git diff --exit-code # this will fail if clang-format made any changes

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
